apiVersion: apps/v1
kind: Deployment
metadata:
  name: horarios
  namespace: deisi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horarios
  template:
    metadata:
      labels:
        app: horarios
    spec:
      containers:
        - name: horarios
          image: ghcr.io/afonso-saaa/horarios:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"