import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          min-h-screen
          flex flex-col justify-start items-center
          bg-black
        `}
      >
        
        <header className=" 
              w-[90vw] pb-3
              flex flex-row justify-between items-center
              text-white 
        ">
          <h1 className="text-4xl font-bold pt-8">Horários</h1>
          {/* <nav className="flex flex-row gap-4">
            <Link  className="hover:underline" href="/">Home</Link>
            <Link className="hover:underline" href="/municipalities">Municípios</Link>
            <Link className="hover:underline" href="/counter">Contador</Link>            
            <Link className="hover:underline" href="/about">Sobre</Link>            
          </nav> */}
        </header>

        <main className="min-h-[70vh] w-[90vw] p-5 rounded-xl bg-gray-100">{children}</main>

        <footer className="text-sm text-white pt-4">2024, DEISI, Lusófona</footer>

      </body>
    </html>
  );
}
