apiVersion: apps/v1
kind: Deployment
metadata:
  name: horarios
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: horarios
  template:
    metadata:
      labels:
        app: horarios
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: horarios
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}